### ISSUE TITLE
Monster Information Not Showing on Patch 13.50.01

### ISSUE THREAD

**Issue by ccrraazzyyman** [sir-wilhelm/SmartHunter#38]
Looks like the latest patch that deployed today broke the monster widget.  The application still shows the damage the hunters have done as well as the buffs, but only the monster information is no longer pulling.

**Comment by sir-wilhelm** [comment]
I'll try and take a look this weekend, I think the offsets will just need to be updated. 

going off: https://github.com/Haato3o/HunterPie/commit/9711e2f252baa997f43b26bec1b8d12341950cb9
the differences are:
https://www.diffchecker.com/Jlfa1h23

**Comment by Emanem** [comment]
FYI - those are also broken on Linux - https://github.com/Emanem/linux-hunter will try to apply similar fixes too...

@sir-wilhelm I'm thinking of implementing a monsters lookup solution similar to HunterPie, where we get the main offset (which I can dynamically look up with memory pattern) and navigate to the 3 active monsters via jumps only `{0x698, 0x0, 0x138, 0x0}`, because identifying the doubly linked list requires offsets and on Linux those may not be the same.

Though I have to say that the solution of navigating the list of all monsters and looking up that memory is more elegant (the one implemented in _SmartHunter_)...
